[workspace]
resolver = "2"
members = [
  "warpforge-api",
  "warpforge-cli",
  "warpforge-visualize",
  "warpforge-executors",
  "catverters",
  "catverters-derive",
  "testfiles-derive",
]

[workspace.package]
edition = "2021"

[workspace.dependencies]
thiserror = "*"
tokio = { version = "*", features = ["macros", "rt", "rt-multi-thread", "io-util", "process", "sync"] }
indexmap = { version = "*", features = ["serde"] }
serde_json = { version = "*", features = ["preserve_order"] }
str-cat = "*"
json-patch = "*"
expect-test = "*"
syscalls = "*"