hard_tabs = true
edition = "2021"
# merge_derives = false
## Doesn't do what it says it does.
##
## Docs claim that true forces adjacent `#[derive()]` blocks to be combined.
##
## Actually what it does is: setting to false causes linebreaks between every param in a single derive.

# max_width = 999999999 ## Kindly twitch less when things change line length.
## max_width is extremely cursed in practice.
## I'd like to say "please don't rewrite the number of linebreaks in my macro parameters"...
## but setting this to a high number seems to cause rustfmt to also try to take many of my enter struct definitions
## and ram *THOSE* onto absurdly long one-liners.
##
## I just want visually stable rules like "if I put structs on multiple lines, they stay that way".
## I'm very, very unimpressed by rustfmt's apparent inability to do that.

# struct_lit_single_line doesn't have a 'preserve' option and i'm mad.
# use_small_heuristics is interesting but vague

# unstable_features = true ## requires the nightly version of the fmt tool, which is trouble.
# overflow_delimited_expr = true ## unstable
# blank_lines_upper_bound = 3 ## unstable
# enum_discrim_align_threshold = 20 ## unstable
# struct_field_align_threshold = 40 ## unstable
