[package]
name = "oci-unpack"
version = "0.1.0"
edition.workspace = true

[dependencies]
oci-spec = "*"
oci-client = "*"
file-mode = "*"
tar = "*"
flate2 = "*"
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
# Used for example binary.
tokio.workspace = true
